const express = require('express');
const router = express.Router();
const axios = require('axios');
require('dotenv').config();

/**
 * Simple dictionary-based translation
 * This is a lightweight approach for common words/phrases
 * 
 * @param {string} text - Text to translate
 * @param {string} targetLanguage - Target language code
 * @returns {string|null} - Translated text or null if not found
 */
function dictionaryTranslate(text, targetLanguage) {
  // This is a very simple implementation
  // In a production system, this would be connected to a proper dictionary database
  
  // Only support Spanish for now as an example
  if (targetLanguage !== 'es') return null;
  
  const dictionary = {
    'hello': 'hola',
    'world': 'mundo',
    'good morning': 'buenos días',
    'thank you': 'gracias',
    'please': 'por favor',
    'yes': 'sí',
    'no': 'no',
    'goodbye': 'adiós',
    'welcome': 'bienvenido',
    'how are you': 'cómo estás',
    'i am fine': 'estoy bien',
    'what is your name': 'cómo te llamas',
    'my name is': 'me llamo',
    'i don\'t understand': 'no entiendo',
    'i don\'t know': 'no sé',
    'i love you': 'te quiero',
    'excuse me': 'disculpe',
    'sorry': 'lo siento',
    'help': 'ayuda',
    'water': 'agua',
    'food': 'comida',
    'restaurant': 'restaurante',
    'hotel': 'hotel',
    'airport': 'aeropuerto',
    'train': 'tren',
    'bus': 'autobús',
    'taxi': 'taxi',
    'car': 'coche',
    'bicycle': 'bicicleta',
    'today': 'hoy',
    'tomorrow': 'mañana',
    'yesterday': 'ayer',
    'time': 'tiempo',
    'hour': 'hora',
    'minute': 'minuto',
    'second': 'segundo',
    'day': 'día',
    'week': 'semana',
    'month': 'mes',
    'year': 'año',
    'money': 'dinero',
    'price': 'precio',
    'cost': 'costo',
    'expensive': 'caro',
    'cheap': 'barato',
    'free': 'gratis',
    'open': 'abierto',
    'closed': 'cerrado',
    'hot': 'caliente',
    'cold': 'frío',
    'big': 'grande',
    'small': 'pequeño',
    'good': 'bueno',
    'bad': 'malo',
    'happy': 'feliz',
    'sad': 'triste',
    'tired': 'cansado',
    'hungry': 'hambriento',
    'thirsty': 'sediento',
    'sick': 'enfermo',
    'healthy': 'saludable',
    'doctor': 'médico',
    'hospital': 'hospital',
    'pharmacy': 'farmacia',
    'medicine': 'medicina',
    'pain': 'dolor',
    'head': 'cabeza',
    'hand': 'mano',
    'foot': 'pie',
    'eye': 'ojo',
    'ear': 'oreja',
    'nose': 'nariz',
    'mouth': 'boca',
    'hair': 'pelo',
    'face': 'cara',
    'body': 'cuerpo',
    'leg': 'pierna',
    'arm': 'brazo',
    'back': 'espalda',
    'stomach': 'estómago',
    'heart': 'corazón',
    'blood': 'sangre',
    'bone': 'hueso',
    'skin': 'piel',
    'muscle': 'músculo',
    'brain': 'cerebro',
    'tooth': 'diente',
    'tongue': 'lengua',
    'finger': 'dedo',
    'toe': 'dedo del pie',
    'knee': 'rodilla',
    'elbow': 'codo',
    'shoulder': 'hombro',
    'chest': 'pecho',
    'neck': 'cuello',
    'wrist': 'muñeca',
    'ankle': 'tobillo',
    'heel': 'talón',
    'sole': 'planta del pie',
    'palm': 'palma',
    'thumb': 'pulgar',
    'index finger': 'dedo índice',
    'middle finger': 'dedo medio',
    'ring finger': 'dedo anular',
    'little finger': 'dedo meñique',
    'nail': 'uña',
    'beard': 'barba',
    'mustache': 'bigote',
    'eyebrow': 'ceja',
    'eyelash': 'pestaña',
    'lip': 'labio',
    'chin': 'barbilla',
    'cheek': 'mejilla',
    'forehead': 'frente',
    'temple': 'sien',
    'jaw': 'mandíbula',
    'throat': 'garganta',
    'lung': 'pulmón',
    'liver': 'hígado',
    'kidney': 'riñón',
    'intestine': 'intestino',
    'stomach': 'estómago',
    'pancreas': 'páncreas',
    'spleen': 'bazo',
    'gallbladder': 'vesícula biliar',
    'bladder': 'vejiga',
    'vein': 'vena',
    'artery': 'arteria',
    'nerve': 'nervio',
    'cell': 'célula',
    'gene': 'gen',
    'chromosome': 'cromosoma',
    'dna': 'adn',
    'protein': 'proteína',
    'vitamin': 'vitamina',
    'mineral': 'mineral',
    'calcium': 'calcio',
    'iron': 'hierro',
    'zinc': 'zinc',
    'magnesium': 'magnesio',
    'potassium': 'potasio',
    'sodium': 'sodio',
    'sugar': 'azúcar',
    'salt': 'sal',
    'fat': 'grasa',
    'carbohydrate': 'carbohidrato',
    'protein': 'proteína',
    'fiber': 'fibra',
    'calorie': 'caloría',
    'diet': 'dieta',
    'exercise': 'ejercicio',
    'sport': 'deporte',
    'run': 'correr',
    'walk': 'caminar',
    'swim': 'nadar',
    'jump': 'saltar',
    'dance': 'bailar',
    'sing': 'cantar',
    'play': 'jugar',
    'read': 'leer',
    'write': 'escribir',
    'speak': 'hablar',
    'listen': 'escuchar',
    'watch': 'mirar',
    'see': 'ver',
    'hear': 'oír',
    'smell': 'oler',
    'taste': 'saborear',
    'touch': 'tocar',
    'feel': 'sentir',
    'think': 'pensar',
    'know': 'saber',
    'understand': 'entender',
    'learn': 'aprender',
    'teach': 'enseñar',
    'study': 'estudiar',
    'work': 'trabajar',
    'job': 'trabajo',
    'office': 'oficina',
    'school': 'escuela',
    'university': 'universidad',
    'student': 'estudiante',
    'teacher': 'profesor',
    'doctor': 'médico',
    'nurse': 'enfermero',
    'engineer': 'ingeniero',
    'lawyer': 'abogado',
    'artist': 'artista',
    'musician': 'músico',
    'actor': 'actor',
    'actress': 'actriz',
    'writer': 'escritor',
    'painter': 'pintor',
    'photographer': 'fotógrafo',
    'designer': 'diseñador',
    'architect': 'arquitecto',
    'scientist': 'científico',
    'researcher': 'investigador',
    'programmer': 'programador',
    'developer': 'desarrollador',
    'manager': 'gerente',
    'director': 'director',
    'president': 'presidente',
    'king': 'rey',
    'queen': 'reina',
    'prince': 'príncipe',
    'princess': 'princesa',
    'father': 'padre',
    'mother': 'madre',
    'son': 'hijo',
    'daughter': 'hija',
    'brother': 'hermano',
    'sister': 'hermana',
    'grandfather': 'abuelo',
    'grandmother': 'abuela',
    'grandson': 'nieto',
    'granddaughter': 'nieta',
    'uncle': 'tío',
    'aunt': 'tía',
    'nephew': 'sobrino',
    'niece': 'sobrina',
    'cousin': 'primo',
    'husband': 'esposo',
    'wife': 'esposa',
    'boyfriend': 'novio',
    'girlfriend': 'novia',
    'friend': 'amigo',
    'neighbor': 'vecino',
    'colleague': 'colega',
    'partner': 'socio',
    'boss': 'jefe',
    'employee': 'empleado',
    'client': 'cliente',
    'customer': 'cliente',
    'passenger': 'pasajero',
    'driver': 'conductor',
    'pilot': 'piloto',
    'sailor': 'marinero',
    'soldier': 'soldado',
    'police officer': 'policía',
    'firefighter': 'bombero',
    'judge': 'juez',
    'lawyer': 'abogado',
    'politician': 'político',
    'citizen': 'ciudadano',
    'foreigner': 'extranjero',
    'tourist': 'turista',
    'immigrant': 'inmigrante',
    'refugee': 'refugiado',
    'prisoner': 'prisionero',
    'victim': 'víctima',
    'witness': 'testigo',
    'suspect': 'sospechoso',
    'criminal': 'criminal',
    'thief': 'ladrón',
    'murderer': 'asesino',
    'terrorist': 'terrorista',
    'hero': 'héroe',
    'villain': 'villano',
    'god': 'dios',
    'devil': 'diablo',
    'angel': 'ángel',
    'demon': 'demonio',
    'ghost': 'fantasma',
    'monster': 'monstruo',
    'alien': 'extraterrestre',
    'robot': 'robot',
    'animal': 'animal',
    'plant': 'planta',
    'tree': 'árbol',
    'flower': 'flor',
    'grass': 'hierba',
    'leaf': 'hoja',
    'root': 'raíz',
    'seed': 'semilla',
    'fruit': 'fruta',
    'vegetable': 'verdura',
    'meat': 'carne',
    'fish': 'pescado',
    'bird': 'pájaro',
    'dog': 'perro',
    'cat': 'gato',
    'horse': 'caballo',
    'cow': 'vaca',
    'pig': 'cerdo',
    'sheep': 'oveja',
    'goat': 'cabra',
    'chicken': 'pollo',
    'duck': 'pato',
    'goose': 'ganso',
    'turkey': 'pavo',
    'rabbit': 'conejo',
    'mouse': 'ratón',
    'rat': 'rata',
    'hamster': 'hámster',
    'guinea pig': 'cobaya',
    'frog': 'rana',
    'toad': 'sapo',
    'snake': 'serpiente',
    'lizard': 'lagarto',
    'turtle': 'tortuga',
    'crocodile': 'cocodrilo',
    'alligator': 'caimán',
    'dinosaur': 'dinosaurio',
    'insect': 'insecto',
    'ant': 'hormiga',
    'bee': 'abeja',
    'wasp': 'avispa',
    'butterfly': 'mariposa',
    'moth': 'polilla',
    'fly': 'mosca',
    'mosquito': 'mosquito',
    'spider': 'araña',
    'scorpion': 'escorpión',
    'crab': 'cangrejo',
    'lobster': 'langosta',
    'shrimp': 'camarón',
    'octopus': 'pulpo',
    'squid': 'calamar',
    'jellyfish': 'medusa',
    'starfish': 'estrella de mar',
    'coral': 'coral',
    'whale': 'ballena',
    'dolphin': 'delfín',
    'shark': 'tiburón',
    'seal': 'foca',
    'walrus': 'morsa',
    'penguin': 'pingüino',
    'eagle': 'águila',
    'hawk': 'halcón',
    'owl': 'búho',
    'parrot': 'loro',
    'peacock': 'pavo real',
    'swan': 'cisne',
    'flamingo': 'flamenco',
    'lion': 'león',
    'tiger': 'tigre',
    'leopard': 'leopardo',
    'cheetah': 'guepardo',
    'bear': 'oso',
    'wolf': 'lobo',
    'fox': 'zorro',
    'deer': 'ciervo',
    'moose': 'alce',
    'elephant': 'elefante',
    'giraffe': 'jirafa',
    'rhinoceros': 'rinoceronte',
    'hippopotamus': 'hipopótamo',
    'zebra': 'cebra',
    'kangaroo': 'canguro',
    'koala': 'koala',
    'panda': 'panda',
    'monkey': 'mono',
    'gorilla': 'gorila',
    'chimpanzee': 'chimpancé',
    'orangutan': 'orangután',
    'human': 'humano',
    'man': 'hombre',
    'woman': 'mujer',
    'boy': 'niño',
    'girl': 'niña',
    'baby': 'bebé',
    'child': 'niño',
    'teenager': 'adolescente',
    'adult': 'adulto',
    'elderly': 'anciano',
    'person': 'persona',
    'people': 'gente',
    'family': 'familia',
    'friend': 'amigo',
    'enemy': 'enemigo',
    'stranger': 'extraño',
    'guest': 'invitado',
    'host': 'anfitrión',
    'neighbor': 'vecino',
    'citizen': 'ciudadano',
    'country': 'país',
    'nation': 'nación',
    'state': 'estado',
    'city': 'ciudad',
    'town': 'pueblo',
    'village': 'aldea',
    'street': 'calle',
    'road': 'carretera',
    'highway': 'autopista',
    'bridge': 'puente',
    'tunnel': 'túnel',
    'building': 'edificio',
    'house': 'casa',
    'apartment': 'apartamento',
    'room': 'habitación',
    'kitchen': 'cocina',
    'bathroom': 'baño',
    'bedroom': 'dormitorio',
    'living room': 'sala de estar',
    'dining room': 'comedor',
    'office': 'oficina',
    'garage': 'garaje',
    'garden': 'jardín',
    'yard': 'patio',
    'pool': 'piscina',
    'park': 'parque',
    'playground': 'parque infantil',
    'school': 'escuela',
    'university': 'universidad',
    'library': 'biblioteca',
    'museum': 'museo',
    'theater': 'teatro',
    'cinema': 'cine',
    'restaurant': 'restaurante',
    'cafe': 'café',
    'bar': 'bar',
    'club': 'club',
    'shop': 'tienda',
    'store': 'tienda',
    'market': 'mercado',
    'supermarket': 'supermercado',
    'mall': 'centro comercial',
    'hospital': 'hospital',
    'clinic': 'clínica',
    'pharmacy': 'farmacia',
    'doctor\'s office': 'consultorio médico',
    'dentist\'s office': 'consultorio dental',
    'police station': 'comisaría',
    'fire station': 'estación de bomberos',
    'post office': 'oficina de correos',
    'bank': 'banco',
    'atm': 'cajero automático',
    'gas station': 'gasolinera',
    'car wash': 'lavado de coches',
    'parking lot': 'aparcamiento',
    'airport': 'aeropuerto',
    'train station': 'estación de tren',
    'bus station': 'estación de autobuses',
    'subway station': 'estación de metro',
    'port': 'puerto',
    'dock': 'muelle',
    'beach': 'playa',
    'mountain': 'montaña',
    'hill': 'colina',
    'valley': 'valle',
    'forest': 'bosque',
    'jungle': 'selva',
    'desert': 'desierto',
    'island': 'isla',
    'lake': 'lago',
    'river': 'río',
    'ocean': 'océano',
    'sea': 'mar',
    'sky': 'cielo',
    'cloud': 'nube',
    'rain': 'lluvia',
    'snow': 'nieve',
    'ice': 'hielo',
    'fog': 'niebla',
    'wind': 'viento',
    'storm': 'tormenta',
    'thunder': 'trueno',
    'lightning': 'relámpago',
    'rainbow': 'arcoíris',
    'sun': 'sol',
    'moon': 'luna',
    'star': 'estrella',
    'planet': 'planeta',
    'earth': 'tierra',
    'mars': 'marte',
    'venus': 'venus',
    'mercury': 'mercurio',
    'jupiter': 'júpiter',
    'saturn': 'saturno',
    'uranus': 'urano',
    'neptune': 'neptuno',
    'pluto': 'plutón',
    'galaxy': 'galaxia',
    'universe': 'universo',
    'space': 'espacio',
    'time': 'tiempo'
  };
  
  // Check if the text is in the dictionary
  const lowerText = text.toLowerCase();
  return dictionary[lowerText] || null;
}

/**
 * Call external translation service
 * 
 * @param {string} text - Text to translate
 * @param {string} targetLanguage - Target language code
 * @returns {Promise<string>} - Translated text
 */
async function callTranslationService(text, targetLanguage) {
  try {
    // This is a placeholder for a real translation service API call
    // In a production environment, you would use a service like Google Translate, DeepL, etc.
    
    // For demonstration purposes, we'll use a mock implementation
    // that simulates a translation service call
    
    // In a real implementation, you would make an API call like:
    // const response = await axios.post('https://translation-service.com/api/translate', {
    //   text: text,
    //   target: targetLanguage
    // }, {
    //   headers: { 'Authorization': `Bearer ${process.env.TRANSLATION_API_KEY}` }
    // });
    // return response.data.translatedText;
    
    // Mock implementation
    return `[Translated to ${targetLanguage}]: ${text}`;
  } catch (error) {
    console.error('Error calling translation service:', error);
    throw new Error('Translation service failed');
  }
}

/**
 * @route POST /translate-text
 * @desc Translate text to target language
 * @access Public
 */
router.post('/', async (req, res) => {
  try {
    const { text, target_language } = req.body;
    
    if (!text || !target_language) {
      return res.status(400).json({ error: 'Text and target language are required' });
    }
    
    // First try dictionary-based translation
    const dictionaryTranslation = dictionaryTranslate(text, target_language);
    
    if (dictionaryTranslation) {
      // If found in dictionary, return immediately
      return res.json({
        original: text,
        translated: dictionaryTranslation,
        target_language,
        source: 'dictionary'
      });
    }
    
    // If not found in dictionary, call translation service
    const translatedText = await callTranslationService(text, target_language);
    
    return res.json({
      original: text,
      translated: translatedText,
      target_language,
      source: 'service'
    });
    
  } catch (error) {
    console.error('Translation error:', error.message);
    res.status(500).json({ error: 'Translation failed' });
  }
});

module.exports = router;