/**
 * generateWordCard.js - Generates flashcards for vocabulary words
 * 
 * This module provides a function to generate flashcards for vocabulary words
 * using context from the article.
 */

/**
 * Generates a flashcard for a vocabulary word
 * @param {string} word - The word to generate a flashcard for
 * @param {string} context - The sentence or context where the word appears
 * @returns {Object} The flashcard data
 */
async function generateWordCard(word, context) {
  try {
    // In a production environment, this would call an AI service like OpenAI
    // For now, we'll use a simple implementation that generates basic flashcards
    
    // Normalize the word (lowercase, trim)
    const normalizedWord = word.toLowerCase().trim();
    
    // Simple dictionary of common words (would be replaced by AI in production)
    const dictionary = {
      'technology': {
        definition: 'methods, systems, and devices which are the result of scientific knowledge',
        example: 'Modern technology has transformed the way we communicate.',
        translation: 'tecnología'
      },
      'science': {
        definition: 'knowledge about the structure and behavior of the natural world',
        example: 'The science of genetics has advanced rapidly in recent years.',
        translation: 'ciencia'
      },
      'article': {
        definition: 'a piece of writing about a particular subject in a newspaper or magazine',
        example: 'I read an interesting article about climate change.',
        translation: 'artículo'
      },
      'development': {
        definition: 'the process of growing or changing and becoming more advanced',
        example: 'The development of new medicines takes many years.',
        translation: 'desarrollo'
      },
      'research': {
        definition: 'a detailed study of a subject to discover new information',
        example: 'Scientists are conducting research on a new vaccine.',
        translation: 'investigación'
      },
      'system': {
        definition: 'a set of connected things or devices that operate together',
        example: 'The solar system consists of the sun and the planets that orbit around it.',
        translation: 'sistema'
      },
      'information': {
        definition: 'facts or details about someone or something',
        example: 'The website provides information about train schedules.',
        translation: 'información'
      },
      'computer': {
        definition: 'an electronic device that processes data according to instructions',
        example: 'She uses her computer to write emails and browse the internet.',
        translation: 'computadora'
      },
      'data': {
        definition: 'facts or information used for reference or analysis',
        example: 'The researchers collected data from thousands of participants.',
        translation: 'datos'
      },
      'digital': {
        definition: 'using or relating to digital signals and computer technology',
        example: 'Most people now use digital cameras instead of film cameras.',
        translation: 'digital'
      }
    };
    
    // Check if the word is in our simple dictionary
    if (dictionary[normalizedWord]) {
      return {
        word: normalizedWord,
        definition: dictionary[normalizedWord].definition,
        example: dictionary[normalizedWord].example,
        translation: dictionary[normalizedWord].translation
      };
    }
    
    // For words not in our dictionary, generate a simple response
    // In a real implementation, this would call an AI API
    return {
      word: normalizedWord,
      definition: `Definition for "${normalizedWord}" (would be generated by AI)`,
      example: `Example sentence using "${normalizedWord}" (would be generated by AI)`,
      translation: `Translation of "${normalizedWord}" (would be generated by AI)`
    };
  } catch (error) {
    console.error('Error generating word card:', error);
    throw new Error('Failed to generate flashcard');
  }
}

module.exports = {
  generateWordCard
};